import { Bai_Jamjuree } from 'next/font/google'
import '../globals.css'

const bai = Bai_Jamjuree({ subsets: ['thai'], weight: ['200', '300', '400', '500', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth bg-primary'>
      <body className={bai.className}>
        <main>
          {children}  
        </main>
      </body>
    </html>
  )
}
