import { Bai_Jamjuree } from 'next/font/google'
import '../globals.css'
import Sidebar from '@/components/Admin/Sidebar'
import AdminHeader from '@/components/Admin/AdminHeader'
import { Toaster } from 'react-hot-toast'

const bai = Bai_Jamjuree({ subsets: ['latin'], weight: ['200', '300', '400', '500', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='scroll-smooth bg-primary'>
      <body className={bai.className}>
        <main className='flex flex-row'>
          <Toaster />
          <Sidebar />
          <section className='flex flex-col h-screen w-full'>
            {/* <AdminHeader /> */}
            <div className='main-container'>
              {children}
            </div>
          </section>
        </main>
      </body>
    </html>
  )
}
